name: CI Pipeline

on:
  push:
    branches: [ sesi31-loadtest ]
  pull_request:
    branches:
      - sesi30-devsecops
      - sesi31-loadtest

jobs:
  lint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 24
          # cache: 'npm'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run ESLint
        run: npm run lint

  unit-test:
    name: Unit Test & Coverage (Jest)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 24
          # cache: 'npm'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run Jest with Coverage
        run: npm test -- --coverage

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@53c2132717906b3a0f7c23f2f8a1eb3d5236b374
        with:
          args: >
            -Dsonar.branch.name=sesi31-loadtest
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  k6-smoke-test:
    name: k6 Smoke Test
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 24
          # cache: 'npm'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Start Express Server in Background  
        run: |
          npm start &
          timeout 30s bash -c 'until curl -s http://127.0.0.1:3000 > /dev/null; do sleep 1; done'

      - name: Setup k6
        uses: grafana/setup-k6-action@b7352342df29c29367a7837059174092b3bc9e65

      - name: Run Smoke Test
        run: k6 run loadtest/script.js